Repository snu-quiqcl/wlm-ui, pull requests merged in 2024-11, with the labels that each got.

#2 Add a GitHub action for ESLint
  .github/workflows/eslint.yml
  wlm-ui/eslint.config.mjs
  wlm-ui/package.json
  wlm-ui/yarn.lock
Labels: repository

#7 Implement sign-in page
  wlm-ui/package.json
  wlm-ui/src/App.tsx
  wlm-ui/src/InitPage/InitPage.tsx
  wlm-ui/src/MainPage/MainPage.tsx
  wlm-ui/src/index.tsx
  wlm-ui/src/store/index.ts
  wlm-ui/src/store/slices/user/user.ts
  wlm-ui/yarn.lock
Labels: enhancement

#17 Implement sign-out button
  wlm-ui/src/MainPage/MainPage.tsx
  wlm-ui/src/store/slices/user/user.ts
Labels: enhancement

#19 Add `"packageManager"` field in `package.json`
  wlm-ui/package.json
Labels: repository

#20 Channel list viewer
  wlm-ui/src/MainPage/ChannelList.tsx
  wlm-ui/src/MainPage/MainPage.tsx
  wlm-ui/src/store/index.ts
  wlm-ui/src/store/slices/channel/channel.ts
Labels: enhancement

#23 Use `??` to check `null`
  wlm-ui/src/store/slices/user/user.ts
Labels: style
